export const APP_NAME = 'appdeveloper';
export const APP_DISPLAY_NAME = 'App Developer Copilot';
export const APP_VERISON = '2.0.1';
export const APP_CONFIG_FILE = 'appdev.json';
export const APP_CONVERSATION_FILE = 'conversation.json';
export const APP_ARCHITECTURE_DIAGRAM_FILE = 'architecture.md';
export const APP_STACK_DIAGRAM_FILE = 'stack.md';
export const SUPA_SQL_FILE_PATH = 'supabase/migrations/init.sql';
export const SUPA_TYPES_WEB_FILE_PATH = 'src/supabase/database.types.ts';
export const SUPA_TYPES_MOBILE_FILE_PATH = 'supabase/database.types.ts';
export const CLASS_DIAGRAM_FILE = 'classDiagram.md';
export const PROJECT_TREE_DIAGRAM_FILE = 'projectTreeDiagram.md';
export const MAX_RETRY_COUNT = 1;

export const ENABLE_TELEMETRY = false; // Config to enable or disable telemetry collection
export const ENABLE_WEB_APP = true; // Config to enable or disable web app creation
export const ENABLE_WEB_STACK_CONFIG = true; // Config to enable or disable web stack configuration
export const ENABLE_BACKEND = true; // Config to enable or disable backend creation
export const ENABLE_AUTHENTICATION = true; // Config to enable or disable authentication
